
import com.mashape.unirest.http.HttpResponse;
import com.mashape.unirest.http.Unirest;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.net.URL;
import java.util.Iterator;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import org.json.JSONArray;
import org.json.JSONObject;


public class Search_Player extends javax.swing.JFrame {

    /**
     * Creates new form Search_Player
     */
    
    JSONObject players;
    public Search_Player() {
        initComponents();
        
        JLabel lb4;
        lb4 = new JLabel();

        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) d.getWidth();
        int y = (int) d.getHeight();
        setSize(x, y);
        lb4.setBounds(0, 0, x, y);
        ImageIcon ic = new ImageIcon("src/MyUploads/cbg.jpg");
        Image ic1 = ic.getImage().getScaledInstance(lb4.getWidth(), lb4.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon ic2 = new ImageIcon(ic1);
        lb4.setIcon(ic2);
        add(lb4);
                setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        
        String filePath = "src/MyUploads/players.txt"; 
        StringBuilder jsonData = new StringBuilder();
        try (BufferedReader br = new BufferedReader(new FileReader(filePath))) {
            String line;
            while ((line = br.readLine()) != null) {
                jsonData.append(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
        JSONObject jsonObject = new JSONObject(jsonData.toString());
        players = jsonObject.getJSONObject("players");
    }
    
    public static String searchPlayer(JSONObject players, String name) {
        Iterator<String> keys = players.keys();

        while (keys.hasNext()) {
            String key = keys.next();
            JSONObject player = players.getJSONObject(key);

            if (player.has("fullname") && player.get("fullname").toString().equalsIgnoreCase(name)) {
                if (player.has("image_path")) {
                    return player.get("image_path").toString();
                }
            }
        }
        return null; // Return null if the player is not found or does not have an image_path
    }

    
    public static BufferedImage scale(BufferedImage src, int w, int h) {
        BufferedImage img
                = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        int x, y;
        int ww = src.getWidth();
        int hh = src.getHeight();
        int[] ys = new int[h];
        for (y = 0; y < h; y++) {
            ys[y] = y * hh / h;
        }
        for (x = 0; x < w; x++) {
            int newX = x * ww / w;
            for (y = 0; y < h; y++) {
                int col = src.getRGB(newX, ys[y]);
                img.setRGB(x, y, col);
            }
        }
        return img;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfff1 = new javax.swing.JTextField();
        bttt1 = new javax.swing.JButton();
        jspp1 = new javax.swing.JScrollPane();
        pp = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("SEARCH  PLAYERS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 60, 450, 50);
        getContentPane().add(tfff1);
        tfff1.setBounds(400, 140, 370, 40);

        bttt1.setBackground(new java.awt.Color(0, 0, 0));
        bttt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        bttt1.setForeground(new java.awt.Color(255, 255, 255));
        bttt1.setText("SEARCH");
        bttt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bttt1);
        bttt1.setBounds(800, 140, 100, 40);

        pp.setBackground(new java.awt.Color(0,0,0,50));

        javax.swing.GroupLayout ppLayout = new javax.swing.GroupLayout(pp);
        pp.setLayout(ppLayout);
        ppLayout.setHorizontalGroup(
            ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 988, Short.MAX_VALUE)
        );
        ppLayout.setVerticalGroup(
            ppLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        jspp1.setViewportView(pp);

        getContentPane().add(jspp1);
        jspp1.setBounds(190, 220, 990, 640);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyUploads/output-onlinegiftools.gif"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 60, 60, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttt1ActionPerformed
        // TODO add your handling code here:
        String name1 =tfff1.getText();
        name1 = name1.replace(" ", "%20");
        try {
            HttpResponse<String> response = Unirest.get("https://cricbuzz-cricket.p.rapidapi.com/stats/v1/player/search?plrN=" + name1)
                    .header("x-rapidapi-key", "340f801646msh9f4da9cc4eafcbfp18dd78jsndb07b1605794")
                    .header("x-rapidapi-host", "cricbuzz-cricket.p.rapidapi.com")
                    .asString();
              if (response.getStatus() == 200) {
                System.out.println("In If");
                pp.removeAll();
                String ans = response.getBody();
              
                System.out.println("Answer ");
            System.out.println(ans);
                int x = 10, y = 10;
                JSONObject mainobj = new JSONObject(ans);
                JSONArray arr = mainobj.getJSONArray("player");

                for (int i = 0; i < arr.length(); i++) {
                    JSONObject obj = (JSONObject) arr.get(i);

                    if (obj.has("id")) {
                        String name = obj.getString("name");
                        String team = obj.getString("teamName");
                        Players_Info p1 = new  Players_Info();
                        String photoPath = searchPlayer(players, name);
        if (photoPath != null) {
            //System.out.println("Photo Path: " + photoPath);
             BufferedImage bi = ImageIO.read(new URL(photoPath));

                bi = scale(bi, p1.jLabel1.getWidth(), p1.jLabel1.getHeight());

                p1.jLabel1.setIcon(new ImageIcon(bi));
        } else {
            p1.jLabel1.setIcon(new ImageIcon("C:\\Users\\user\\Documents\\NetBeansProjects\\CRICKETBUZZ Priyaaz\\src\\MyUploads\\dummy-image.jpg"));
            System.out.println("Player not found with the name: " + name);
        }
                        System.out.println("demooo");
                     

                        p1.kl.setText(name);
                        p1.kl1.setText(team);
                        p1.setBounds(x, y, 298, 308);

                        if (x < 616) {
                            x = x + 318;
                        } else {
                            y = y + 316;
                            x = 10;
                        }
                        pp.add(p1);
                        pp.setBackground(Color.black);
                        pp.repaint();
                        pp.revalidate();
                    }
                }
                pp.setPreferredSize(new Dimension(1000, y + 308));

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "No Player found with this name ");
            ex.printStackTrace();
        }
    }//GEN-LAST:event_bttt1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        User_Home uh=new User_Home();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
 
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_Player().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttt1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jspp1;
    private javax.swing.JPanel pp;
    private javax.swing.JTextField tfff1;
    // End of variables declaration//GEN-END:variables
}
